---
apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: nifi
  labels:
    app: nifi

spec:

  type: LoadBalancer

  selector:

    app: nifi

  ports:

  - protocol: TCP

    port: 8080

    targetPort: 8080

    name: nifi

  - protocol: TCP

    port: 8082

    targetPort: 8082

    name: cluster

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
  labels:
    name: nifi
    app: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: nifi
      restartPolicy: Always
      containers:
      - name: nifi
        image: jjino/kubernete-nifi-cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: nifi
        - containerPort: 8082
          name: cluster
        env:
          - name: NIFI_WEB_HTTP_PORT
            value: "8080"
          - name: NIFI_CLUSTER_IS_NODE
            value: "true"
          - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
            value: "8082"
          - name: NIFI_CLUSTER_NODE_ADDRESS
            value: "nifi"
          - name: NIFI_ZK_CONNECT_STRING
            value: "zk-cs.nifi.svc.cluster.local:2181"
          - name: NIFI_ELECTION_MAX_WAIT
            value: "1 min"
        livenessProbe:
          exec:
            command:
              - pgrep
              - java
        readinessProbe:
          exec:
            command:
              - pgrep
              - java
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 512Mi

