---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: nifi
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
    "statefulset.kubernetes.io/pod-name": zookeeper-0
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
    name: zk
  - protocol: TCP
    port: 5111
    targetPort: 5111
    name: cmd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: nifi
  labels:
    name: zookeeper
    app: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: zookeeper
      restartPolicy: Always
      containers:
      - name: zookeeper
        image: zookeeper:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: zk
        - containerPort: 5111
          name: cmd
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
        livenessProbe:
          exec:
            command:
              - which
              - java
        readinessProbe:
          tcpSocket:
              port: 2181
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
